name: Cloud.gov deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{secrets.CF_SERVICE_USER}}
          cf_password: ${{secrets.CF_SERVICE_AUTH}}
          cf_vars_file: vars.development.yml
          cf_org: gsa-datagov
          cf_space: ${{vars.ENVIRONMENT_NAME}}

  bail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: core.setFailed('Checks failed, not deploying')
